### ISSUE TITLE
Docs: german translation

### ISSUE THREAD

**Issue by kilian-funk** [lordmauve/pgzero#144]
WIP at [https://github.com/kilian-funk/pgzero-german](https://github.com/kilian-funk/pgzero-german)

**Comment by nicolaipoehner** [comment]
Are you still working on this?

**Comment by lordmauve** [comment]
I would assume this effort has stalled. If you want to contribute you could certainly fork kilian-funk/pgzero-german and continue development. If you do that, please link to your fork/branch in this issue, and also open a PR to kilian-funk/pgzero-german in case @kilian-funk is interested to merge it.

**Comment by nicolaipoehner** [comment]
I partly translated the documentation now: https://github.com/nicolaipoehner/pgzero-german/tree/master/doc. I translated and adapted the index, installation, introduction, and from-scratch-file. I think that this should be enough since this is enough for the first steps. I don't think its useful to also translate all the technical sites (e.g. hooks, built-ins) since most of it is code anyway (which is english). I believe it should allow students to get a first glance and then link the english site for further information. There might still be a couple of mistakes and typos in there, which I will fix in the next couple of days. What do you think?

**Comment by nicolaipoehner** [comment]
PS: This is the link to the german documentation: https://pgzero-german.readthedocs.io/de/latest/index.html

**Comment by nicolaipoehner** [comment]
What do you think @lordmauve? Do you want to link it to the original page? Is it ok if I integrate a subpage with (more) example projects of Pygame Zero in the German version? I think this could allow students and teachers to get a first idea of the possibilites of Pygame Zero.

**Comment by jensens** [comment]
I would really love to see a kind of "official" translation provided on the official site as it is for Chinese, Japanese and Slovakian already. If there is any help needed please let me now.
![Screenshot from 2020-08-24 11-12-05](https://user-images.githubusercontent.com/157140/91026240-ccdf6a80-e5fa-11ea-8e7c-a87416ef9838.png)

**Comment by lordmauve** [comment]
@nicolaipoehner Hi, I can connect that up to the site. However ReadTheDocs now requires that you make me (`mauve` on readthedocs.org) a maintainer of the pgzero-german docs project in order to add it as a translation.

**Comment by nicolaipoehner** [comment]
@lordmauve I added you to the project on readthedocs.org. You should be able to add the german translation now.

**Comment by lordmauve** [comment]
I have added it! It should appear as the official German translation now.

**Comment by nicolaipoehner** [comment]
Quick question: In my German translation the logo of Pygame Zero doesn't appear. Any idea how to fix this? Simply adding the HTML code doesn't seem to be working.
