### ISSUE TITLE
Add a triangle or polygon function

### ISSUE THREAD

**Issue by r0the** [lordmauve/pgzero#203]
Hi

I use pgzero in my high school courses. Aside from actors, I often use the screen.draw functions to draw simple shapes. What I really miss there is a way to draw more generic shapes. It would be great, if triangle and/or polygon functions could be added to the SurfacePainter class.

I could provide a pull request.

**Comment by lordmauve** [comment]
Sure; following the convention it would be `screen.draw.polygon()`/`screen.draw.filled_polygon()`.

**Comment by MrD-compSci** [comment]
As a teacher wanting to start off with simple draw commands - adding the following commands would allow for programming exercises similar to what other starter languages can do:

Needed for simple drawings:
-------------------------------
screen.draw.triangle
screen.draw.ellipse ( or screen.draw.oval )

Additional request:
--------------------
screen.draw.floodfill (start filling at a point, keep the paint spreading until a boundary colour 
                                        is encountered)


Thanks,

MR.D

**Comment by lordmauve** [comment]
I've just merged @r0the's code for polygons, so that covers drawing triangles.

The flood fill algorithm is not provided by Pygame. That's because it is likely not really fast enough for a game framework, even if implemented in C. It isn't really a game programming algorithm - it's an image processing algorithm. If you are thinking about image processing in general, then Pillow is the go-to library, and that [does have a flood-fill method](https://pillow.readthedocs.io/en/5.1.x/reference/ImageDraw.html?highlight=floodfill#PIL.ImageDraw.PIL.ImageDraw.floodfill). I've never tried using Pillow with Pygame/Pygame Zero but it ought to be possible to create a `pygame.Surface` and `PIL.Image` that share their underlying buffer by using  [Surface.get_buffer()](https://www.pygame.org/docs/ref/surface.html#pygame.Surface.get_buffer) and [PIL.Image.from_buffer()](https://pillow.readthedocs.io/en/5.1.x/reference/Image.html#PIL.Image.frombuffer) - taking care to get the pixel formats correct on both ends.

Please can you file a new issue for drawing ellipses?
