### ISSUE TITLE
Translations: Why not use Sphinx-intl?

### ISSUE THREAD

**Issue by jensens** [lordmauve/pgzero#229]
I wonder why translations need to go in an own repository (download/add https://pygame-zero.readthedocs.io/en/stable/contributing.html#helping-to-translate-the-documentation) instead of using the official Sphinx-Intl? This would simplify i18n/l10n, including keeping track of changes.
https://www.sphinx-doc.org/en/master/usage/advanced/intl.html

**Comment by lordmauve** [comment]
Yeah, that's how I would do it if I was paying for translations or I have a highly skilled and engaged translation team. I think the approach of forking the docs is really easy for beginner contributors to follow.

Of course, keeping track of changes is a problem, but I'd propose to just open issues with those projects, linking to a diff of the changes to docs in each release. It's crude, and a little more work to merge and translate a diff at the same time, but it's way more accessible than using an additional suite of tools, rather than just a text editor.

**Comment by jensens** [comment]
Translating gettext files is dumb easy. Well, to me it seems forking, keeping stuff in sync and communicating several repositories (...and more) is not easier, but probably its a matter of taste. Anyway - it would be great to have a complete, always up to date  German (and many other) translation (s) linked on the RTD default-page. I would help (for the German part), here, but seeing my future self diffing stuff if there's software that can do this for me seems a bit awkward.

Thanks anyway for pgzero - such a great thing for getting people on-boarded to Python!
