### ISSUE TITLE
Notes on the tutorial

### ISSUE THREAD

**Issue by lordmauve** [lordmauve/pgzero#29]
Originally reported by: **Andrew McCarthy (Bitbucket: [a_mccarthy](https://bitbucket.org/a_mccarthy), GitHub: Unknown)**

----------------------------------------

Some nit-picks on the tutorial that might confuse beginners:

- The acceptable range for red/green/blue values is not given.

- The difference between the draw() and update() functions is not described. Code works in either block.

- While trying to click the alien, the mouse pointer is only visible when moving. (While testing on Raspberry Pi)

- ~~"(but the sound will play repeatedly)" is confusing - suggests sound will play in a loop. Perhaps remove this?~~

- After the "refactor", the new set_alien_hurt() function has sound and image lines reversed. After adding the "clock.schedule..." the order is reversed back again.

- The schedule_unique method accepts integers. Perhaps use 1 instead of 1.0, or maybe instead give a fractional value like 0.5 to demonstrate the precision available?

----------------------------------------
- Bitbucket: https://bitbucket.org/lordmauve/pgzero/issue/29

**Comment by lordmauve** [comment]
*Original comment by* **PK Shiu (Bitbucket: [pkshiu](https://bitbucket.org/pkshiu), GitHub: [pkshiu](https://github.com/pkshiu))**:

----------------------------------------

How about given a set of default color constants so that beginners do not have to understand RGB?

**Comment by lordmauve** [comment]
*Original comment by* **Daniel Pope (Bitbucket: [lordmauve](https://bitbucket.org/lordmauve), GitHub: [lordmauve](https://github.com/lordmauve))**:

----------------------------------------

Apparently kids love playing with RGB triples. It's like mixing paint. So that's not a problem.

But actually, most of the API accepts colour names as strings already.

**Comment by lordmauve** [comment]
*Original comment by* **PK Shiu (Bitbucket: [pkshiu](https://bitbucket.org/pkshiu), GitHub: [pkshiu](https://github.com/pkshiu))**:

----------------------------------------

I actually think the fact that pygame allows string names is a *bad* thing. It is not good programming practice to have mixed data types, let alone using strings. Depending on the purpose of pgz, if we are using this tool to teach programming concepts, constants is a much more important concept than using strings as aliaes. (This also relates to issue #30, image.alien vs 'alien'. 

OMHO of course, coming from teaching programming using Scratch.

**Comment by lordmauve** [comment]
*Original comment by* **Daniel Pope (Bitbucket: [lordmauve](https://bitbucket.org/lordmauve), GitHub: [lordmauve](https://github.com/lordmauve))**:

----------------------------------------

I've reworded the "(but the sound will play repeatedly)" in 3dec950 as "(but the sound will play on each click)"

**Comment by MarkAColes** [comment]
I am working on issue

**Comment by MarkAColes** [comment]
Updates on progress:

The acceptable range for red/green/blue values is not given. **Already fixed**

The difference between the draw() and update() functions is not described. Code works in either block.
**Added in details about why two are used**

While trying to click the alien, the mouse pointer is only visible when moving. (While testing on Raspberry Pi)

"(but the sound will play repeatedly)" is confusing - suggests sound will play in a loop. Perhaps remove this?

After the "refactor", the new set_alien_hurt() function has sound and image lines reversed. After adding the "clock.schedule..." the order is reversed back again. **Refactored the code snippets to all follow the same order to remove confusion.**

The schedule_unique method accepts integers. Perhaps use 1 instead of 1.0, or maybe instead give a fractional value like 0.5 to demonstrate the precision available? **Changed the value to be 1 instead of 1.0**
